services:
  caddy:
    profiles: ["caddy", "all"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy
    network_mode: host
    restart: unless-stopped
    environment:
      - KC_HOSTNAME=${KC_HOSTNAME:?KC_HOSTNAME is not set}
      - KC_HTTP_PORT=${KC_HTTP_PORT:?KC_HTTP_PORT is not set}
      - LINKWARDEN_HOSTNAME=${LINKWARDEN_HOSTNAME:?LINKWARDEN_HOSTNAME is not set}
      - LINKWARDEN_PORT=${LINKWARDEN_PORT:?LINKWARDEN_PORT is not set}
      - NEXTCLOUD_HOSTNAME=${NEXTCLOUD_HOSTNAME:?NEXTCLOUD_HOSTNAME is not set}
      - NEXTCLOUD_PORT=${NEXTCLOUD_PORT:?NEXTCLOUD_PORT is not set}
      - VAULTWARDEN_HOSTNAME=${VAULTWARDEN_HOSTNAME:?VAULTWARDEN_HOSTNAME is not set}
      - VAULTWARDEN_PORT=${VAULTWARDEN_PORT:?VAULTWARDEN_PORT is not set}
      - OPENBAO_HOSTNAME=${OPENBAO_HOSTNAME:?OPENBAO_HOSTNAME is not set}
      - OPENBAO_PORT=${OPENBAO_PORT:?OPENBAO_PORT is not set}
      - IMMICH_HOSTNAME=${IMMICH_HOSTNAME:?IMMICH_HOSTNAME is not set}
      - IMMICH_PORT=${IMMICH_PORT:?IMMICH_PORT is not set}
      - OFFLINE_NOTION_PORT=${OFFLINE_NOTION_PORT:?OFFLINE_NOTION_PORT is not set}
      - OFFLINE_NOTION_HOSTNAME=${OFFLINE_NOTION_HOSTNAME:?OFFLINE_NOTION_HOSTNAME is not set}
      - OFFLINE_NOTION_V1_HOSTNAME=${OFFLINE_NOTION_V1_HOSTNAME:?OFFLINE_NOTION_V1_HOSTNAME is not set}
      - FORGEJO_HOSTNAME=${FORGEJO_HOSTNAME:?FORGEJO_HOSTNAME is not set}
      - FORGEJO_PORT=${FORGEJO_PORT:?FORGEJO_PORT is not set}
    volumes:
      - ${VOLUME_BASE_DIR:?VOLUME_BASE_DIR is not set}/caddy/data:/data
      - ${VOLUME_BASE_DIR:?VOLUME_BASE_DIR is not set}/caddy/config:/config
