services:
  caddy:
    profiles: ["caddy"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy
    network_mode: host
    restart: unless-stopped
    environment:
      - KC_HOSTNAME=${KC_HOSTNAME:?KC_HOSTNAME is not set}
      - KC_HTTP_PORT=${KC_HTTP_PORT:?KC_HTTP_PORT is not set}
      - LINKWARDEN_HOSTNAME=${LINKWARDEN_HOSTNAME:?LINKWARDEN_HOSTNAME is not set}
      - LINKWARDEN_PORT=${LINKWARDEN_PORT:?LINKWARDEN_PORT is not set}
      - NEXTCLOUD_HOSTNAME=${NEXTCLOUD_HOSTNAME:?NEXTCLOUD_HOSTNAME is not set}
      - NEXTCLOUD_PORT=${NEXTCLOUD_PORT:?NEXTCLOUD_PORT is not set}
      - VAULTWARDEN_HOSTNAME=${VAULTWARDEN_HOSTNAME:?VAULTWARDEN_HOSTNAME is not set}
      - VAULTWARDEN_PORT=${VAULTWARDEN_PORT:?VAULTWARDEN_PORT is not set}
    volumes:
      - ${VOLUME_BASE_DIR:?VOLUME_BASE_DIR is not set}/caddy/data:/data
      - ${VOLUME_BASE_DIR:?VOLUME_BASE_DIR is not set}/caddy/config:/config
