services:
  keycloak_postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${KC_DB_NAME:?KC_DB_NAME is not set}
      POSTGRES_USER: ${KC_DB_USERNAME:?KC_DB_USERNAME is not set}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD:?KC_DB_PASSWORD is not set}
    volumes:
      - ${VOLUME_BASE_DIR:?VOLUME_BASE_DIR is not set}/keycloak/postgresql:/var/lib/postgresql

  keycloak_server:
    image: quay.io/keycloak/keycloak:26.5.3
    command:
      - start
      - --import-realm
    environment:
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: ${KC_HOSTNAME:?KC_HOSTNAME is not set}
      KC_HOSTNAME_STRICT: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/${KC_DB_NAME:?KC_DB_NAME is not set}
      KC_DB_USERNAME: ${KC_DB_USERNAME:?KC_DB_USERNAME is not set}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:?KC_DB_PASSWORD is not set}
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: ${KC_HTTP_RELATIVE_PATH:?KC_HTTP_RELATIVE_PATH is not set}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:?KC_BOOTSTRAP_ADMIN_USERNAME is not set}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:?KC_BOOTSTRAP_ADMIN_PASSWORD is not set}
      KC_HTTP_PORT: ${KC_HTTP_PORT:?KC_HTTP_PORT is not set}
    restart: unless-stopped
    depends_on:
      keycloak_postgres:
        condition: service_started
    # volumes:
    #   - ./keycloak:/opt/keycloak/data/import:ro
    ports:
      - "${KC_HTTP_PORT}:${KC_HTTP_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${KC_HTTP_PORT}/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s