include:
  - caddy/docker-compose.yaml
  - keycloak/docker-compose.yaml
  - linkwarden/docker-compose.yaml
  - nextcloud/docker-compose.yaml
  - vaultwarden/docker-compose.yaml
  - openbao/docker-compose.yaml
